name: CI/CD
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        perl: [ '5.32', '5.30', '5.28', '5.26', '5.24', '5.22', '5.20', '5.18', '5.16', '5.14', '5.12', '5.10', '5.8' ]
        exclude:
          # https://github.com/shogo82148/actions-setup-perl/issues/225
          - { os: windows-latest, perl: '5.8'  }
          - { os: windows-latest, perl: '5.10' }
          - { os: windows-latest, perl: '5.12' }
    name: 🐪 Perl ${{ matrix.perl }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry # this option only used on Windows
      - name: Build and Test
        # Have to build on Windows to get scripts\psql.bat.
        run: |
          perl -V
          cpanm --installdeps .
          perl Build code
          prove -lv t
  publish:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && needs.test.result == 'success'
    name: 🐳 Docker Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker build --pull -t ${DOCKER_USER}/pg_prove:latest -t ${DOCKER_USER}/pg_prove:$(perl bin/pg_prove -V | awk '{print $2}') -f dist/Dockerfile .
      - name: Publish to Registry
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
          docker push ${DOCKER_USER}/pg_prove
